# =========================
# Identificacion del proyecto
# =========================
sonar.projectKey=alephsub0_Aleph-calcs
sonar.projectName=Aleph-calcs
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
# =========================
# Quality Gate
# =========================
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300